pipeline:
  build:
    image: node
    secrets:  [ gcloud_key ]
    commands:
     - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
     - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
     - apt update
     - apt install yarn -y
     - npm install --prefix ./slspatcherui
     - npm install
     - cd ./slspatcherui
     - npm run-script ebuild
  build_tag_deploy: 
    image: node
    secrets:  [ gcloud_key ]
    when:
      event: tag
    commands:
      - npm install -g github-release-cli
      - >-
        github-release upload \
        --owner frostebite \
        --repo slspatcherui \
        --tag "v0.1.0" \
        --name "v0.1.0" \
        --body "This release contains bug fixes and imporvements, including:\n..." \
        archive.zip index.html app.min.css app.min.js
