pipeline:
  build:
    image: node
    secrets:  [ gcloud_key ]
    commands:
     - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     - apt update
     - apt install yarn -y
     - npm install --prefix ./slspatcherui
     - npm install
     - cd ./slspatcherui
     - npm run-script ebuild
