pipeline:
  build:
    image: electronuserland/builder:wine
    secrets:  [ gh_token ]
    commands:
     - apt-get update > /dev/null
     - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
     - sh -c 'echo "deb https://dl.yarnpkg.com/debian/ stable main" >> /etc/apt/sources.list.d/yarn.list'
     - apt update > /dev/null
     - apt install yarn -y
     - node -v
     - npm cache clean -f
     - npm install -g n
     - n stable
     - n latest
     - node -v
     - yarn --version
     # build ui
     - cd ./slspatcherui
     - yarn install -y > /dev/null
     - yarn build
     # build app wrapper
     - cd ..
     - yarn install > /dev/null
     - yarn dist
  build_tag_deploy: 
    image: electronuserland/builder:wine
    secrets:  [ ]
    when:
      event: tag
    commands:
      - apt install --reinstall base-files lsb-release lsb-base -y > /dev/null
      - apt-get update > /dev/null
      - apt install nodejs npm curl yarn -y > /dev/null
      - npm install -g github-release-cli
      - >-
        github-release upload \
        --owner $${DRONE_REPO_NAMESPACE} \
        --repo $${DRONE_REPO_NAME} \
        --tag $${DRONE_TAG} \
        --name $${DRONE_TAG} \
        --body "This release contains bug fixes and imporvements, including:\n..." \
        latest.yml slspatcher-setup-$${DRONE_TAG}.exe