pipeline:
  build:
    image: node
    secrets:  [ gcloud_key ]
    commands:
     - npm install --prefix ./slspatcherui
     - npm install
     - npm run-script build --prefix ./slspatcherui
     - npm run-script start